/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
	'solarmanpv adapter settings': {
		'en': 'Adapter settings for solarmanpv',
		'de': 'Adaptereinstellungen für solarmanpv',
		'ru': 'Настройки адаптера для solarmanpv',
		'pt': 'Configurações do adaptador para solarmanpv',
		'nl': 'Adapterinstellingen voor solarmanpv',
		'fr': "Paramètres d'adaptateur pour solarmanpv",
		'it': "Impostazioni dell'adattatore per solarmanpv",
		'es': 'Ajustes del adaptador para solarmanpv',
		'pl': 'Ustawienia adaptera dla solarmanpv',
		'zh-cn': 'solarmanpv的适配器设置'
	},
	'option1': {
		'en': 'option1',
		'de': 'Option 1',
		'ru': 'Опция 1',
		'pt': 'Opção 1',
		'nl': 'Optie 1',
		'fr': 'Option 1',
		'it': 'opzione 1',
		'es': 'Opción 1',
		'pl': 'opcja 1',
		'zh-cn': '选项1'
	},
	'option2': {
		'en': 'option2',
		'de': 'Option 2',
		'ru': 'вариант 2',
		'pt': 'opção 2',
		'nl': 'Optie 2',
		'fr': 'Option 2',
		'it': 'opzione 2',
		'es': 'opcion 2',
		'pl': 'Opcja 2',
		'zh-cn': '选项2'
	}
};